from pathlib import Path
p=Path('/mnt/data/mhtour_v48/android/app/src/main/java/com/mhtour/audio/MainActivity.kt')
s=p.read_text()
s=s.replace('import io.livekit.android.room.Room\n', 'import io.livekit.android.room.Room\nimport io.livekit.android.token.TokenRequestOptions\nimport io.livekit.android.token.TokenSource\n')
s=s.replace('import java.net.HttpURLConnection\nimport java.net.URL\n', 'import java.util.UUID\n')
old='''    // AUTO ONLINE: URL dapat ditanam saat build melalui Gradle property\n    // MH_TOUR_API_BASE_URL. Jika kosong, pengguna dapat memasukkannya dari\n    // menu server lanjutan. Tidak ada lagi ketergantungan pada hotspot 192.168.43.1.\n    private val prefs: SharedPreferences by lazy { getSharedPreferences("mh_tour_settings", MODE_PRIVATE) }\n    private val configuredServerUrl: String\n        get() = prefs.getString("server_url", BuildConfig.MH_TOUR_API_BASE_URL)?.trim().orEmpty()\n'''
new='''    // AUTO ONLINE TEST: token dibuat oleh LiveKit Cloud Development Token Server.\n    // Token server ID bukan secret dan boleh ditanam di APK untuk pengujian.\n    // Untuk production, ganti ke endpoint token server milik MH Tour.\n    private val developmentTokenServerId: String\n        get() = BuildConfig.MH_TOUR_TOKEN_SERVER_ID.trim()\n'''
if old not in s: raise SystemExit('header old not found')
s=s.replace(old,new)
# Remove normalize function
start=s.find('    private fun normalizeHttpBaseUrl(')
if start!=-1:
    end=s.find('    private fun requestMicIfNeeded()', start)
    s=s[:start]+s[end:]
# Replace guide create block
old='''        create.setOnClickListener {\n            if (!requireInternet()) return@setOnClickListener\n            create.isEnabled = false; state.text = "Membuat sesi..."\n            lifecycleScope.launch {\n                try {\n                    val r = requestSession(name.text.toString().trim().ifBlank { "Guide" })\n                    currentCode = r.getString("code"); code.text = currentCode\n                    qr.setImageBitmap(makeQrBitmap("MHTOUR|JOIN|$configuredServerUrl|$currentCode")); qr.visibility = View.VISIBLE; qrHint.visibility = View.VISIBLE\n                    shareQr.isEnabled = true\n                    state.text = "Sesi siap — bagikan kode atau QR di atas ke jemaah."; talk.isEnabled = true\n                } catch (e: Exception) { state.text = "Gagal membuat sesi: ${e.message}" }\n                finally { create.isEnabled = true }\n            }\n        }\n'''
new='''        create.setOnClickListener {\n            if (!requireInternet()) return@setOnClickListener\n            create.isEnabled = false; state.text = "Membuat ruang audio online..."\n            try {\n                val generatedCode = "UM${(100000..999999).random()}"\n                val generatedRoomName = "mh-tour-${UUID.randomUUID()}"\n                currentCode = "$generatedCode|$generatedRoomName"\n                code.text = generatedCode\n                // QR tidak membawa API Secret. Token server ID sudah ditanam di APK.\n                val payload = "MHTOUR|JOIN|$generatedCode|$generatedRoomName"\n                qr.setImageBitmap(makeQrBitmap(payload)); qr.visibility = View.VISIBLE; qrHint.visibility = View.VISIBLE\n                shareQr.isEnabled = true\n                state.text = "Ruang online siap — bagikan kode atau QR ke jemaah."\n                talk.isEnabled = true\n            } catch (e: Exception) {\n                state.text = "Gagal membuat ruang: ${e.message}"\n            } finally { create.isEnabled = true }\n        }\n'''
if old not in s: raise SystemExit('guide create not found')
s=s.replace(old,new)
# Replace share listener
old='''        shareQr.setOnClickListener {\n            currentCode?.let { c -> shareText("MH Tour — Rombongan: $c\\n\\nScan QR untuk bergabung. Kode rombongan: $c") }\n        }\n'''
new='''        shareQr.setOnClickListener {\n            currentCode?.let { raw ->\n                val parts = raw.split("|", limit = 2)\n                val c = parts.firstOrNull().orEmpty()\n                val roomName = parts.getOrNull(1).orEmpty()\n                shareText("MH Tour — Rombongan: $c\\n\\nScan QR untuk bergabung. Kode rombongan: $c\\nRoom: $roomName")\n            }\n        }\n'''
if old not in s: raise SystemExit('share not found')
s=s.replace(old,new)
# Replace guide token request
old='''                    val token = requestToken(currentCode!!, name.text.toString().trim().ifBlank { "Guide" }, "guide")\n                    room?.disconnect(); room = connectLiveKit(token)\n'''
new='''                    val session = parseSessionCode(currentCode ?: error("Sesi belum dibuat"))\n                    room?.disconnect(); room = connectLiveKit(session.roomName, name.text.toString().trim().ifBlank { "Guide" })\n'''
if old not in s: raise SystemExit('guide token not found')
s=s.replace(old,new)
# Replace jamaah join token request
old='''            lifecycleScope.launch {\n                try { val token = requestToken(c, name.text.toString().trim().ifBlank { "Jemaah" }, "jamaah"); room?.disconnect(); room = connectLiveKit(token); currentCode = c; state.text = "TERHUBUNG • Menunggu Guide"; indicator.text = "●  SIAP MENDENGARKAN" }\n                catch (e: Exception) { state.text = "Gagal bergabung: ${e.message}"; indicator.text = "◉  KONEKSI GAGAL"; room?.disconnect(); room = null }\n                finally { join.isEnabled = true }\n            }\n'''
new='''            lifecycleScope.launch {\n                try {\n                    val session = parseSessionCode(c)\n                    room?.disconnect(); room = connectLiveKit(session.roomName, name.text.toString().trim().ifBlank { "Jemaah" })\n                    currentCode = "$c|${session.roomName}"\n                    state.text = "TERHUBUNG • Menunggu Guide"; indicator.text = "●  SIAP MENDENGARKAN"\n                }\n                catch (e: Exception) { state.text = "Gagal bergabung: ${e.message}"; indicator.text = "◉  KONEKSI GAGAL"; room?.disconnect(); room = null }\n                finally { join.isEnabled = true }\n            }\n'''
if old not in s: raise SystemExit('jamaah join not found')
s=s.replace(old,new)
# Replace QR parser block
old='''                if (parts.size >= 4 && parts[0] == "MHTOUR" && parts[1] == "JOIN") {\n                    val scannedServer = parts[2].trim()\n                    if (scannedServer.startsWith("http://") || scannedServer.startsWith("https://")) {\n                        prefs.edit().putString("server_url", scannedServer.removeSuffix("/")).apply()\n                    }\n                }\n                val code = if (parts.size >= 4) parts[3].trim().uppercase() else payload.removePrefix("MHTOUR|JOIN|").trim().uppercase()\n                if (code.matches(Regex("UM[A-Z0-9]{4,20}"))) {\n                    jamaahScreenWithCode(code)\n                } else {\n'''
new='''                if (parts.size >= 4 && parts[0] == "MHTOUR" && parts[1] == "JOIN") {\n                    val scannedCode = parts[2].trim().uppercase()\n                    val scannedRoom = parts[3].trim()\n                    if (scannedCode.matches(Regex("UM[0-9]{6}")) && scannedRoom.startsWith("mh-tour-")) {\n                        jamaahScreenWithCode("$scannedCode|$scannedRoom")\n                    } else {\n                        Toast.makeText(this, "QR rombongan MH Tour tidak valid", Toast.LENGTH_LONG).show()\n                    }\n                } else {\n                    val code = payload.removePrefix("MHTOUR|JOIN|").trim().uppercase()\n                    if (code.matches(Regex("UM[A-Z0-9]{4,20}"))) jamaahScreenWithCode(code)\n                    else Toast.makeText(this, "QR bukan QR rombongan MH Tour yang valid", Toast.LENGTH_LONG).show()\n                }\n                /* legacy server-based QR is intentionally not used in AUTO ONLINE mode */\n                if (false) {\n'''
if old not in s: raise SystemExit('qr parser not found')
s=s.replace(old,new)
# Need close braces corresponding if false block: inspect after replacement; easiest replace the old tail segment
old='''                if (false) {\n                    Toast.makeText(this, "QR bukan QR rombongan MH Tour yang valid", Toast.LENGTH_LONG).show()\n                }\n'''
new='''                if (false) {\n                    Toast.makeText(this, "QR bukan QR rombongan MH Tour yang valid", Toast.LENGTH_LONG).show()\n                }\n'''
# no-op
# Replace bottom request functions and connect
start=s.find('    private fun httpPost(')
end=s.find('    override fun onDestroy()', start)
if start==-1 or end==-1: raise SystemExit('bottom block not found')
newblock='''    private data class SessionInfo(val code: String, val roomName: String)\n\n    private fun parseSessionCode(value: String): SessionInfo {\n        val parts = value.trim().split("|", limit = 2)\n        val code = parts.firstOrNull().orEmpty().uppercase()\n        val roomName = parts.getOrNull(1).orEmpty()\n        require(code.matches(Regex("UM[0-9]{6}"))) { "Kode rombongan tidak valid" }\n        require(roomName.startsWith("mh-tour-") && roomName.length > 9) { "QR belum berisi room online yang valid" }\n        return SessionInfo(code, roomName)\n    }\n\n    private suspend fun connectLiveKit(roomName: String, participantName: String): Room = withContext(Dispatchers.IO) {\n        require(developmentTokenServerId.isNotBlank()) { "Token server MH Tour belum dikonfigurasi" }\n        val source = TokenSource.fromDevelopmentTokenServer(developmentTokenServerId)\n        val response = source.fetch(\n            TokenRequestOptions(\n                roomName = roomName,\n                participantName = participantName\n            )\n        ).getOrThrow()\n        require(response.serverUrl.startsWith("ws://") || response.serverUrl.startsWith("wss://")) {\n            "Alamat LiveKit tidak valid"\n        }\n        require(response.participantToken.isNotBlank()) { "Token LiveKit kosong" }\n\n        val newRoom = LiveKit.create(applicationContext)\n        newRoom.connect(\n            url = response.serverUrl,\n            token = response.participantToken,\n            options = ConnectOptions(\n                autoSubscribe = true,\n                audio = false,\n                video = false\n            )\n        )\n        newRoom\n    }\n\n'''
s=s[:start]+newblock+s[end:]
p.write_text(s)
